### ISSUE TITLE
how to excute ?

### ISSUE THREAD

**Issue by changchichung** [ayushbhat/shotpy#3]
I can use python shotpy.py to make a screenshot and upload to imgur now.
But I cant run  shotpy 
```
(.ve) administrator@administrator-ThinkPad-T470:~/git/shotpy$ shotpy
shotpy: command not found
(.ve) administrator@administrator-ThinkPad-T470:~/git/shotpy$ 
```
how do I run shotpy directly , instead of using python shotpy ?

**Comment by 1ay1** [comment]
go to the directory containing shotpy.py, open terminal, and then run the following commands as su( root):
`cp shotpy.py /usr/bin/`
`cd /usr/bin`
`mv shotpy.py shotpy`
`chmod +x shotpy`
